### ISSUE TITLE
upgrade to miniz >2.0 for Zip64 support and listing zips with >65535 files?

### ISSUE THREAD

**Issue by jefferis** [r-lib/zip#11]
I have a zip file with >80,000 files but I can only list the first 65535, see:

https://github.com/richgel999/miniz/issues/35

Is there any chance that you could switch to miniz 2.0.7?

**Comment by gaborcsardi** [comment]
Closed by 1d052d5b615daefaefab64e7e587afb768b58119

**Comment by jefferis** [comment]
Many thanks! I’ll try it out later. It looks like it was a fairly large change, but I guess it is probably good to be on the newer codebase.
