### ISSUE TITLE
Absolute file paths in version 2.0.0

### ISSUE THREAD

**Issue by emmamendelsohn** [r-lib/zip#26]
Seems like there might be an issue with absolute paths in the `files` argument of `zip()`?  I'm getting the following error in version 2.0.0 but not 1.0.0:
```
zip::zip(zipfile = "foo.zip", files = here::here("foo.csv"))

Error in zip_internal(zipfile, files, recurse, compression_level, append = FALSE,  : 
  zip error: `Cannot add file `/Users/emmamendelsohn/project_folder/foo.csv` to archive `/Users/emmamendelsohn/project_folder/foo.zip`` in file `zip.c:394`
```
Changing the file path from absolute to relative works:
```
zip::zip(zipfile = "foo.zip", files =  "foo.csv")
```
The `zipfile` argument works regardless of path type.

<details>
<summary>Session Info</summary>

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_0.2.1 here_0.1     zip_2.0.0   

loaded via a namespace (and not attached):
[1] compiler_3.5.1  backports_1.1.3 rprojroot_1.3-2 tools_3.5.1     fs_1.2.6       
[6] Rcpp_1.0.0      rlang_0.3.1    
```
</details>

**Comment by gaborcsardi** [comment]
Are you sure you want absolute path in the zip archive? THat's usually not what  people want, please consider using `zip::zipr()` that stores relative paths. See the docs.

**Comment by emmamendelsohn** [comment]
That makes sense, I will switch to `zip::zipr()`.  It might help someone in the future to have a more informative error when using absolute paths in `zip::zip()` given the break in functionality between versions.  Thanks for your help.

**Comment by gaborcsardi** [comment]
Oh, that was unintended, I did not know it broke. Will fix.

**Comment by gaborcsardi** [comment]
Actually, I think I'll deprecate `zip()`, because it is just not what people want.
