### ISSUE TITLE
File Timestamps are not preserved 

### ISSUE THREAD

**Issue by jeanchristophechiem** [r-lib/zip#27]
Dear all,
I need to preserve the timestamps of the files to zip (creation date). 
The zip process used in this library applies the compression date to all file within the zip. 
I did not find any package implementing this behaviro, while common zipping GUI (winrar/zip) do preserve the creation date.
Could this become a future feature in this package, or would you suggest other options?

Many Thanks for this useful package.

**Comment by gaborcsardi** [comment]
Can you please provide a reproducible example, and also information about your platform, because for me zip always preserves the time stamps:
```r
❯ file.mtime("README.md")
[1] "2019-02-23 22:02:36 GMT"

❯ tmp <- tempfile(fileext=".zip")
❯ zip::zipr(tmp, "README.md")
❯ zip::zip_list(tmp)
   filename compressed_size uncompressed_size           timestamp permissions
1 README.md            1447              4038 2019-02-23 22:02:36         644

❯ exdir <- tempfile()
❯ zip::unzip(tmp, exdir  = exdir)

❯ file.mtime(file.path(exdir, "README.md"))
[1] "2019-02-23 22:02:36 GMT"
```

**Comment by jeanchristophechiem** [comment]
Dear Gabor,

I was using an older version of your package which only had zip::zip function not zipr.
Removing/updating the package and using zip::zipr fixed the trick.
Apology for the inconvenience and thanks for the support.
Br.,
jc
