### ISSUE TITLE
How to add a file under a subfolder with zipr and keep the folder structure

### ISSUE THREAD

**Issue by dracodoc** [r-lib/zip#41]
`zipr` seem to be a improvement to `zip`, however I don't know how to achieve this:
- Using the example in help, this folder structure
```
foo
  bar
      file1
      file1a
  bar2
      file2
foo2
  file3
```
- sometimes I want to zip some files under a folder selectively, i.e. the folder foo but not all the files. With `zip` I just use relative path and add "bar/file1", "bar2". 
- With `zipr` the same usage will result `file1` in top level and lost the `bar` subfolder structure.

How can I do this with `zipr`?

I think the problem here is that zip actually need two set of instructions:
1. the input file list
2. how to arrange input files in the zip

Usually it's assumed the result is same with input structure, so the behavior that zipr put bar/file1 at top level is a little bit strange to me, and I'm not sure if absolute path problem is relevant here as we are using relative paths.

**Comment by gaborcsardi** [comment]
Yeah, I agree that this is not great. But then maybe we should un-deprecate `zip()` and just use that. 

I would also add an alias to `zipr()` to make it more expression what it does, and add examples to the manual. Would that make sense?

**Comment by dracodoc** [comment]
Yes that will be great. zip has served my purpose well and un-deprecate it will solve the problem. Thanks!

**Comment by AshesITR** [comment]
This will be possible once #50 is merged.

```r
zipr("x.zip", files = c("bar/file1", "bar2"), keys = c("file1", "bar2"))
```

**Comment by gaborcsardi** [comment]
`zip` is not deprecated any more, so this should be easier.
