### ISSUE TITLE
Unzip when file conatins UTF-8 characters in R

### ISSUE THREAD

**Issue by MislavSag** [r-lib/zip#42]
I want to unzip folder and rename files from rhat folder in R.

My try with zip package:

```
zip::unzip("my.path", exdir = "mydocument")
unzip_files <- list.files("mydocument", full.names = TRUE)
for (j in seq_along(unzip_files)) {
  file.rename(unzip_files[j], "somefilename")
}
```

The problem is that files in zip document contains UTF-8 characters:

> 16900-19 odb. parcelacija katastar - službeno  više uložaka, čl. 145.doc

but when unzipped the files looks like this:

> 16900-19 odb. parcelacija katastar - sluÅ¾beno  viÅ¡e uloÅ¾aka, Äl. 145

and I can't rename it beacuse it has this strange characters.

So I need to unzip folder but keep UTF-8 characters or somehow rename file with this strange chracters.

**Comment by gaborcsardi** [comment]
What is your operating system?

**Comment by MislavSag** [comment]
windows 10
