### ISSUE TITLE
Zip without parent directory

### ISSUE THREAD

**Issue by Minhoux** [r-lib/zip#43]
I use zipr successfully but I get the structure:
Temporary/media....
I want the zip file to content what the temporary folder contents, without this unuseful Temporary/parent folder.

The rest is perfect, the stucture is kept and everything.

Any idea how to do that?

**Comment by gaborcsardi** [comment]
Then specify the list of files to `zipr()` instead of the directory they are in.

**Comment by gaborcsardi** [comment]
Closing, as I believe that this is solved. If not, please reopen.
