### ISSUE TITLE
Cannot download the package because of the executable file "cmdunzip.exe"

### ISSUE THREAD

**Issue by rosinnia** [r-lib/zip#49]
Our corporate policy prevents downloading any zip folder with executable file (i.e., cmdzip.exe). Any suggestion to get around this (of course not to ask my company to change the policy for me)? 
I have also tried to install the source file "zip_2.0.4.tar" but got the following error message: 
*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -O3 -Wall  -std=gnu99 -mtune=generic miniz.c zip.c tools/cmdzip.c -o tools/cmdzip.exe
make: c:/Rtools/mingw_32/bin/gcc: Command not found
make: *** [Makevars.win:9: tools/cmdzip.exe] Error 127
ERROR: compilation failed for package 'zip'

It seemed to me that this also had something to do with the "cmdzip.exe" file. 
Thanks!

**Comment by gaborcsardi** [comment]
To install the source package, you need Rtools (https://cran.r-project.org/bin/windows/Rtools/) But this is also an exe file, so you probably can't install it. :(

I'll think about how we could work around having an .exe in the zip binary package....

**Comment by gaborcsardi** [comment]
Do you think you would be able to download the file if we just renamed `cmdzip.exe` to something else? Do you have a way to try that?

**Comment by rosinnia** [comment]
Thanks a lot for following up! I found a solution to this one. It turned out that my company had an internal website loading all these packages inside the firewall. I think the name change might benefit some of the others who had a similar firewall issue as what I had run into. It might be worth trying. Please let me know if you want me to test it once the name is changed.

Thanks,
Hua

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AshesITR** [comment]
An alternative approach to `unzip_process` and `zip_process` would be using the R functions in a new R process using `callr`. This would eliminate the need for executables altogether at the cost of a little overhead of starting up R instead of a minimal tool.

**Comment by gaborcsardi** [comment]
The whole point of them is to avoid the startup overhead. Which is 300-500ms, and very significant if you need to uncompress ~100 zip files, e.g. when installing R packages.

**Comment by AshesITR** [comment]
I see. Vectorisation of `unzip` would solve that, no?
Something along `unzip(list.files("zips", pattern = "\\.zip$"), exdir = "out")` to extract all zips to the same location and `unzip(c("z1.zip", "z2.zip"), exdir = c("o1", "o2"))` for differing locations.

**Comment by gaborcsardi** [comment]
No, it would not, because we also want to run the unzip subprocesses in parallel.

**Comment by gaborcsardi** [comment]
I am going to close this now, until this comes up again. It might be so rare that it is not worth spending time on it.

**Comment by rosinnia** [comment]
Thanks for following up. Yeah, agreed.

Hua

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nigeldoyle** [comment]
So... I think this is related. The current (2.2.0) package tries to go off and install zip.exe directly from github. Our web gateway/proxy/firewall blocks this (well, technically it pushes a web user via a "are you sure you want to go against company policy?" screen before allowing) and therefore even if I download the package and install from a local file, it still relies on an internet connection... Is there a way around this? I CAN download the 'https://github.com/rwinlib/zip/blob/master/zip.exe?raw=true' file myself manually, but of course I can't then force the install to look at my local download... can I?

I am more than happy to accept a workaround, but currently this inability to install zip is stopping me from installing the very useful package "usethis", as zip is a dependency of that! I'm afraid I'm too ignorant on packages to know whether there's an option set I can use to avoid this...

**Comment by gaborcsardi** [comment]
Can you install the binary build of zip?

**Comment by nigeldoyle** [comment]
Thanks for the speedy response! Sadly not:
> install.packages(".../R-model/zip_2.2.0.zip")
Installing zip [2.2.0] ...
	OK [installed binary]
Error: DESCRIPTION file at 'G:/.../renv/staging/5/zip/DESCRIPTION' is empty

Is this tied to the use of renv??

**Comment by nigeldoyle** [comment]
NB: I'm running: R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by nigeldoyle** [comment]
If I start a new rstudio session without renv, I get a different error (which confuses me even more):

> install.packages(".../R-model/zip_2.2.0.zip")
Installing package into ‘C:/Users/xxx/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘.../R-model/zip_2.2.0.zip’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by nigeldoyle** [comment]
apologies - that worked - I just needed the type="win.binary" - thanks for your help!
