### ISSUE TITLE
withCallingHandlers does not suppress custom message

### ISSUE THREAD

**Issue by jeroen** [r-lib/zip#52]
I want to use zip in gert to archive exactly the files tracked by git (so no auto-recurse). I don't think this can be done with `zipr` so we use the soft-deprecated `zip` function:

```r
zip::zip("archive.zip", gert::git_ls()$path)
```

The documentation recommends to do this:

```r
withCallingHandlers(
  zip::zip(...),
  deprecated = function(e) NULL)
```

But that doesn't actually suppress the message (in R 4.0)

```r
test_zip <- function(){
  file.copy(R.home('COPYING'), 'COPYING')
  zip::zip('test.zip', 'COPYING', recurse = FALSE)
}

withCallingHandlers(test_zip(), deprecated = function(e) NULL)
## Note: zip::zip() is deprecated, please use zip::zipr() instead
```

This does work though: `suppressMessages(test_zip())`

**Comment by gaborcsardi** [comment]
The condition handler should call the restart, actually, like this:

```r
test_zip <- function(){
  file.copy(R.home('COPYING'), 'COPYING')
  zip::zip('test.zip', 'COPYING', recurse = FALSE)
}

withCallingHandlers(
  test_zip(), 
  deprecated = function(e) invokeRestart("muffleMessage")
)
```

**Comment by gaborcsardi** [comment]
But I'll un-deprecate `zip::zip`, so all this will go away, actually.

**Comment by gaborcsardi** [comment]
They are not deprecated any more, so this is gone.

**Comment by jeroen** [comment]
Thanks!
