### ISSUE TITLE
2.2.1 cannot handle absolute path in Linux

### ISSUE THREAD

**Issue by lz100** [r-lib/zip#69]
```bash
cd ~/Desktop
touch text.txt
```

```r
zip::zip("test.zip", "/home/xx/Desktop/text.txt")
```
 > zip error: `Cannot add file `/home/xx/Desktop/test.txt` to archive `test.zip`` in file `zip.c:348`

unless I add `mode = "cherry-pick"`. If this is expected, I would appreciate for better documentation to explain and better error than just "zip.c:348".

**Comment by gaborcsardi** [comment]
Yeah, the error message is not great, I can try to improve that.

As for the docs, the two modes are documented in the manual, here-ish: https://github.com/r-lib/zip/blob/master/R/zip.R#L12 If you think we could improve that, please let me know. Thanks.

**Comment by gaborcsardi** [comment]
I'll leave this issue open to improve the error message.

**Comment by lz100** [comment]
Maybe in the document, say something like "absolute path for files will not work in 'mirror mode'".  I am not sure the reason, zip cannot resolve the relative link between the current working directory and the absolute path? I think you can explain it better.

**Comment by gaborcsardi** [comment]
Hmmm, the docs say 
```
#' (Absolute paths are also kept. Note that this might result
#' non-portable archives: some zip tools do not handle zip archives that
#' contain absolute file names, or file names that start with `../` or
#' `./`. zip warns you if this should happen.)
```
but that's not the behavior I am seeing and `zip()` errors when I try to add a file with an absolute path, at least on Unix. I'll try Windows as well and update the docs.
