### ISSUE TITLE
Unzip crashes when exdir ends with "/"

### ISSUE THREAD

**Issue by fsteinhi** [r-lib/zip#81]
v2.2.0: 
  Unzip crashes when exdir ends with "/"
  Error msg:   
`    Error in unzip(zipfile, exdir = "input/", junkpaths = FALSE,  : 
      zip error: `Cannot extract file `XYZ.csv`` in file `zip.c:211``
  if exdir does not end with "/" it is working.

v2.1.1
  Unzip did not crash when exdir ends with "/"
  if exdir does not end with "/" it crashes.

Summary:
  v2.2 and v2.1 do not behave equal. 
  Is this on purpose or could be adjusted?

**Comment by klin333** [comment]
in addition to different behaviors of v2.1.1 and v2.2.0 for trailing "/" for exdir argument, there is also different behavior for leading "/" in files argument.

I know, best practices for zip files states that files within zip should not have leading "/", but often that's outside our control. 

v2.1.1: no problems with unzip
```
tmpd <- tempdir()
zip::unzip(zipfile, files = "/file1.txt", exdir = tmpd)
```

v2.2.0
error message:
```
Error in zip::unzip(zipfile, files = "/file1.txt",  : 
  zip error: `Cannot extract file `/file1.txt`` in file `zip.c:211`
```

**Comment by gaborcsardi** [comment]
I cannot reproduce this with zip v2.2.0:
```
> zip("test.zip", c("NAMESPACE", "R"))
> unzip("test.zip", exdir = "input/")
> dir("input")
[1] "NAMESPACE" "R"

> packageVersion("zip")
[1] '2.2.0'
```

**Comment by gaborcsardi** [comment]
Nevertheless we now remove the trailing `/` from `exdir`.

**Comment by klin333** [comment]
forgot to mention, i had errors when tested on Windows. might be a windows thing...

**Comment by gaborcsardi** [comment]
Yeah, I thought about that, I did try on Windows. OTOH it might be a base R thing on older Windows, let me try.

FWIW I also cannot reproduce the problem with extracting files with absolute paths, but I'll try that as well on Windoows.

**Comment by gaborcsardi** [comment]
Yeah, I can reproduce it on older R, but the commit I just added fixes it.

**Comment by gaborcsardi** [comment]
I can also reproduce the issue with extracting absolute paths on Windows.
