### ISSUE TITLE
R_ZIPCMD is not set under Windows (returns an empty string)

### ISSUE THREAD

**Issue by sjentsch** [r-lib/zip#84]
It appears as if the environment variable `R_ZIPCMD` is not correctly populated under Windows (it returns an empty string instead of pointing to the `zip.exe`). As a consequence, `utils::zip` isn't working when called (fails to create the ZIP-file but unfortunately doesn't throw an error message).
Is there any reason for that and could you add some form of fallback behaviour so that `zip.exe` is correctly found. Perhaps, there is something in the software setup I am using (zip as a dependency inside jamovi) that prevents correct setup? Any ideas?

**Comment by gaborcsardi** [comment]
I am afraid that this package has nothing to do with `R_ZIPCMD ` and `utils::zip()`, the place for reporting bugs about the utils package is the R bug tracker: https://bugs.r-project.org/
